### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by NicoHood** [sffjunkie/astral#11]
Hi,
I try to build astral for archlinux and got some problems with the recent 1.4.1 tag. You've fixed those issues in the master branch, it would be nice if you could update those.

The issue is the missing setup.cfg which is loaded by `version=versioneer.get_version(),` and other parts in the setup. Maybe you can just tag a release 1.4.2 (also gpg signed? #10 )

**Comment by flak3** [comment]
Use the latest commit as a workaround, there is no proper reason to make another release as there is no change which would justify all their users updating it. ([example](https://github.com/flak3/reposource/blob/master/main/python-astral/PKGBUILD))

**Comment by sffjunkie** [comment]
Version 1.5 is now up on PyPi.

I have monkeypatched distutils so the setup.cfg settings local to my machine can be in a separate file. This means setup.cfg is now in the sdist.
