### ISSUE TITLE
Moon phase 24?

### ISSUE THREAD

**Issue by neutralvibes** [sffjunkie/astral#16]
Getting a moon phase of 24 but there is no info on what string that phase number relates to.

Using version 1.6

**Comment by sffjunkie** [comment]
Added more text to the docs to hopefully clarify your issue. Please look at https://astral.readthedocs.io/en/latest/ to see if it answers your question.

**Comment by neutralvibes** [comment]
Thanks, that clears things up for me. Thanks for your efforts.
