### ISSUE TITLE
Make dependancy on requests optional

### ISSUE THREAD

**Issue by RouquinBlanc** [sffjunkie/astral#19]
Hi,

For one of our project we want to use astral to determine sun course and all the great stuff provided by astral. The only thing is: we are completely offline, and want to keep our python env light.

As we are never going to use all the GoogleGeocoder feature (no network), it would be really nice to make the dependency on `requests` optional: right now, if we don't install `requests`, we cannot even load `Location` or `Astral` with the default `AstralGeocoder` which does require AFAICS connectivity...

Would it be possible to only raise an error if we try to instanciate a `GoogleGeocoder` in case that `requests` is not installed?

We are very careful with which dependencies we integrate, and `requests` package with all its dependancies is a big waste of space...

Thanks!

**Comment by sffjunkie** [comment]
Fixed in version 1.7.1
