### ISSUE TITLE
PySolar comparison

### ISSUE THREAD

**Issue by paulocheque** [sffjunkie/astral#20]
Hey guys, do you know how Astral algorithms are compared to PySolar?

**Comment by sffjunkie** [comment]
Looking at PySolar's code it looks to me that it is concerned with, for example, the radiation of the sun in Watts at a position on the earth and has a quality needed for the purposes of scientific analysis.

Whereas Astral is more concerned with whether the sun is above or below the horizon and when the changes between the various states of the sun (dawn, dusk etc.) occur.

I wrote Astral to calculate when I needed to automate the turning on or off of my lighting and only needed low accuracy (that and the fact that I was too lazy to attempt to build PyEphem on Windows with all the occult Visual C incantations that building binaries entails).

The calculations for Astral came from the NOAA website https://www.esrl.noaa.gov/gmd/grad/solcalc/calcdetails.html
