### ISSUE TITLE
Adding more cities to AstralGeocoder - for example Zakopane, Poland

### ISSUE THREAD

**Issue by matkoniecz** [sffjunkie/astral#22]
Would you accept PR adding more cities to AstralGeocoder?

**Comment by sffjunkie** [comment]
No, I don't think I would, there's probably too many in there already. I can add a parameter to the Astral class __init__ to add more locations to AstralGeocoder, if that helps.

**Comment by matkoniecz** [comment]
Yes, it would be helpful.

**Comment by sffjunkie** [comment]
An `add_locations` method has been added to AstralGeocoder in version 1.10 to add locations to the database.
