### ISSUE TITLE
Lookup of moon phase name

### ISSUE THREAD

**Issue by PanderMusubi** [sffjunkie/astral#23]
Please add a lookup of the [moon phase name](https://en.wikipedia.org/wiki/Lunar_phase#Phases_of_the_Moon).

A suggestion of doing this is by returning a string for a float value:
* phase < 1 returns `New moon`
* phase >= 1 and phase < 7 returns `Waxing crescent`
* phase >= 7 and phase < 8 returns `First quarter`
* phase >= 8 and phase < 14 returns `Waxing gibbous`
* phase >= 14 and phase < 15 returns `Full moon`
* phase >= 15 and phase < 21 returns `Waning gibbous`
* phase >= 21 and phase < 22 returns `Last quarter`
* phase >= 22 returns `Waning crescent`
* the rest returns an empty string

Implementation should support localization of the names via gettext. Implementation could even be in exiting method `moon_phase()` when `rtype=str`.

PS   The exact values above should be reviewed by someone with more in-depth knowledge of this subject.

**Comment by PanderMusubi** [comment]
Alternative implementation for int is:
* phase == 0 returns `New moon`
* phase > 0 and phase < 7 returns `Waxing crescent`
* phase == 7 returns `First quarter`
* phase > 7 and phase < 14 returns `Waxing gibbous`
* phase == 14 returns `Full moon`
* phase > 14 and phase < 21 returns `Waning gibbous`
* phase == 21 returns `Last quarter`
* phase > 21 returns `Waning crescent

I have been testing a bit with this and get for both implementation sometimes two consecutive days with the same moon phase. For example for int implementation (date, phase in int, name, symbol, phase in float):

    2019-08-15 14 Full moon 🌕 14.111222222222224
    2019-08-16 14 Full moon 🌕 14.889000000000001
    ...
    2019-10-21 21 Last quarter 🌗 21.033444444444445
    2019-10-22 21 Last quarter 🌗 21.96677777777778

This is of course to be expected, but what is the way to solve this? Choose the day closest to the value of 14, 21, etc. and filter out the other day?

**Comment by PanderMusubi** [comment]
I think I have come up with a working implementation, please see https://github.com/PanderMusubi/lunar-phase-calendar/blob/master/generate.py

**Comment by PanderMusubi** [comment]
Are you interested in integrating my implementation into astral? If not, could you make a reference to it in your documentation?

**Comment by sffjunkie** [comment]
My intention was to only provide the calculation of the numbers and not interpret them any further than that so I don't think I will integrate the functionality from your work, but I am happy to provide a reference to it in the docs.

**Comment by PanderMusubi** [comment]
Super. Thanks you.
