### ISSUE TITLE
Weird moon phase calculations, float return value does not seem to work

### ISSUE THREAD

**Issue by princzp** [sffjunkie/astral#24]
Thanks for the effort, astral is a great piece of work,very much appreciated.
I did some calculations with it and compared the results with some diaries one can buy in bookshops as well as with moon phases calendar, such as this one:
https://www.timeanddate.com/moon/phases/?year=2019
They all agree and slightly disagree with astral's calculations, sometimes there is a shift, always max. 1 day  compared with the others. I've also observed it yields the very same moon age for two consecutive calendar days before such a skew happens, so I guess it is because of the integer return value of the moon phase. Tried to go for float return value but no matter what I pass for rtype, I always get int.

**Comment by princzp** [comment]
I just checked the other opened tickets and came to realise the previous one (#23) is similar, i.e. he is also mentioning two consecutive calendar days yield the same moon age. What I am adding is notable moon age (0, 7, 14, 21 for new moon, 1stq, full moon, 3rdq respectively) dates may skew a day here and there, compared with timeanddate. It can be seen for 2019 as well.

But once again, thanks for the effort.

**Comment by PanderMusubi** [comment]
Please, see also https://github.com/sffjunkie/astral/issues/23 Could you please check the output?

**Comment by princzp** [comment]
Thank you, it's great. 

For now, my (#24) ticket can actually be closed. My biggest struggle was I could not invoke astral's moon_phase with float precision, I was always getting back an int. Now I have seen the proper invocation in your ticket earlier and started a very similar function on my own, now that I can see the float return values. (I.e. see if the previous day and today would yield the same return value and leave one of them and "fake" the other one. I think the problem is a bit more sophisticated, sometimes it's the day before that is triggering the phase too early, so I'd when rendering the phase of today, I'd actually check yesterday and tomorrow, and would come to a decision seeing all three values.)

Thanks for the effort, I might just reuse your function (day_to_moon_phase_and_accurate_code).

**Comment by princzp** [comment]
Question: what do you think, is it OK (i.e. polite) if I just close this ticket at this pont? I can see a close button on this page, but don't know the local customs.
Thanks.

**Comment by princzp** [comment]
OK, I am closing this ticket. It''s either fixed or taken care already in another ticket (#23). Sorry for the noise.
Once again, thank you for the effort.
