### ISSUE TITLE
solar_depression has no effect

### ISSUE THREAD

**Issue by Gravitar64** [sffjunkie/astral#27]
Tried the package with city_name = 'Berlin'

The calculated values for dawn are always the same, no matter what value solar_depression has ('civil', 'nautical' or 'astronomical').

Here the code-snippet:
`from astral import Astral 
LOCATION = 'Berlin'

a = Astral()
a.solar_depression = 'civil'
city = a[LOCATION]
print(LOCATION, city.region, city.timezone) 
sun = city.sun(date=arrow.now(), local=True)
print(sun)`

and the output (print sun) for 'civil'

{'dawn': datetime.datetime(2019, 1, 29, 4, 1, 26, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'sunrise': datetime.datetime(2019, 1, 29, 7, 52, 54, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'noon': datetime.datetime(2019, 1, 29, 12, 19, 19, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'sunset': datetime.datetime(2019, 1, 29, 16, 45, 44, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'dusk': datetime.datetime(2019, 1, 29, 20, 37, 12, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>)}

and for 'nautical':

{'dawn': datetime.datetime(2019, 1, 29, 4, 1, 26, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'sunrise': datetime.datetime(2019, 1, 29, 7, 52, 54, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'noon': datetime.datetime(2019, 1, 29, 12, 19, 19, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'sunset': datetime.datetime(2019, 1, 29, 16, 45, 44, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'dusk': datetime.datetime(2019, 1, 29, 20, 37, 12, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>)}

and for 'astronomical':

{'dawn': datetime.datetime(2019, 1, 29, 4, 1, 26, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'sunrise': datetime.datetime(2019, 1, 29, 7, 52, 54, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'noon': datetime.datetime(2019, 1, 29, 12, 19, 19, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'sunset': datetime.datetime(2019, 1, 29, 16, 45, 44, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>), 'dusk': datetime.datetime(2019, 1, 29, 20, 37, 12, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>)}

The values for dawn and dusk are far to low/high. The correct values should be (UTC-Time from https://sunrise-sunset.org):

{'results': {'sunrise': '2019-01-29T06:52:06+00:00', 'sunset': '2019-01-29T15:46:55+00:00', 'solar_noon': '2019-01-29T11:19:31+00:00', 'day_length': 32089, 'civil_twilight_begin': '2019-01-29T06:14:41+00:00', 'civil_twilight_end': '2019-01-29T16:24:21+00:00', 'nautical_twilight_begin': '2019-01-29T05:33:16+00:00', 'nautical_twilight_end': '2019-01-29T17:05:46+00:00', 'astronomical_twilight_begin': '2019-01-29T04:53:12+00:00', 'astronomical_twilight_end': '2019-01-29T17:45:50+00:00'}, 'status': 'OK'}

**Comment by sffjunkie** [comment]
The sun_utc calc has been fixed in 1.10. The results are now within a minute of those from sunrise-sunset.org which is all the NOAA spreadsheet, that Astral's calcs come from, guarantees.
