### ISSUE TITLE
Current date doesn't take timezone into account

### ISSUE THREAD

**Issue by therefromhere** [sffjunkie/astral#29]
`Location.sun` etc will default to the system date if it's not specified.  I think it should take tz into account if `local=True`?

I hit this issue today in NZ, where the clocks just changed.  Calculated dawn (etc) was off by 1 hour since the machine tz wasn't the same the location tz, therefore this morning the date was defaulting to yesterday, and therefore wasn't using daylight saving.

**Comment by sffjunkie** [comment]
In version 2.0 two functions have been added `now` and `today` which are timezone aware and are used where required e.g. in the Location class

**Comment by therefromhere** [comment]
Thanks!
