### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by sffjunkie** [sffjunkie/astral#37]
As part of refactoring remove all Python 2 support?

**Comment by hugovk** [comment]
Please see PR #39.

**Comment by danielhoherd** [comment]
Legacy python is legacy. The existing code should suffice for anybody who needs to run 2.x. I say go with 3.x only.

**Comment by sffjunkie** [comment]
Version 2.0 drops Python 2.x and requires 3.6 or greater due to use of dataclasses.

**Comment by hugovk** [comment]
Great, I'll close PR #39 then :)
