### ISSUE TITLE
hard paths in setup.cfg breaks install under buildout

### ISSUE THREAD

**Issue by dotnetslash** [sffjunkie/astral#4]
Hard coding paths in your setup.cfg breaks installing under buildout.

It's also surprising when using simple `python setup.py build` If build attempted higher in the file system, they could try to write in / (or above!).

Suggest you remove those lines from prod distributions.

**Comment by zpriddy** [comment]
I agree. 

When fixing problems with OSX I had to delete the file while working on it.

**Comment by sffjunkie** [comment]
setup.cfg is now removed from the repository and only used locally.

**Comment by sffjunkie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [buildbot & setup.cfg](https://trello.com/c/MIxcPi7L/2-buildbot-setupcfg)
