### ISSUE TITLE
Sun Calculations for Custom Location Wrong

### ISSUE THREAD

**Issue by jethornton** [sffjunkie/astral#45]
Using the example at https://astral.readthedocs.io/en/latest/ when I put my latitude and longitude in the returned times are completely off.

`#!/usr/bin/python3

import datetime
from astral.sun import sun
from astral import LocationInfo
from astral.location import Location
city = LocationInfo("London", "England", "Europe/London", 51.5, -0.116)
pbmo = LocationInfo("Poplar Bluff", "Midwest", "US/Central", 36.873512, -90.488008)

print((
    f"Information for {city.name}/{city.region}\n"
    f"Timezone: {city.timezone}\n"
    f"Latitude: {city.latitude:.02f}; Longitude: {city.longitude:.02f}\n"
))

s = sun(city.observer, date=datetime.date(2020, 2, 11))
print((
    f'Dawn:    {s["dawn"]}\n'
    f'Sunrise: {s["sunrise"]}\n'
    f'Noon:    {s["noon"]}\n'
    f'Sunset:  {s["sunset"]}\n'
    f'Dusk:    {s["dusk"]}\n'
))

print((
    f"Information for {pbmo.name}/{pbmo.region}\n"
    f"Timezone: {pbmo.timezone}\n"
    f"Latitude: {pbmo.latitude:.02f}; Longitude: {pbmo.longitude:.02f}\n"
))

s = sun(pbmo.observer, date=datetime.date(2020, 2, 11))
print((
    f'Dawn:    {s["dawn"]}\n'
    f'Sunrise: {s["sunrise"]}\n'
    f'Noon:    {s["noon"]}\n'
    f'Sunset:  {s["sunset"]}\n'
    f'Dusk:    {s["dusk"]}\n'
))
`
Running this results in:
`john@d10cave:~/gitlocal/coop2$ ./sun2.py
Information for London/England
Timezone: Europe/London
Latitude: 51.50; Longitude: -0.12

Dawn:    2020-02-11 06:47:32.053221+00:00
Sunrise: 2020-02-11 07:23:12.648323+00:00
Noon:    2020-02-11 12:14:41+00:00
Sunset:  2020-02-11 17:06:54.384574+00:00
Dusk:    2020-02-11 17:42:38.338837+00:00

Information for Poplar Bluff/Midwest
Timezone: US/Central
Latitude: 36.87; Longitude: -90.49

Dawn:    2020-02-11 12:28:12.640188+00:00
Sunrise: 2020-02-11 12:55:27.838617+00:00
Noon:    2020-02-11 18:16:10+00:00
Sunset:  2020-02-11 23:37:22.438327+00:00
Dusk:    2020-02-12 00:04:38.943368+00:00
`

Thanks for Astral, I've been using it in my current chicken coop to open and close the door for a couple of years now. Just upgrading the new coop to Python 3 and Astral 2.

JT

**Comment by jethornton** [comment]
For my location today:
Sunrise 6:54
Meridian 12:15
Sunset 17:37

JT

**Comment by sffjunkie** [comment]
The example is correct but slightly confusing as the times being returned by the `astral.sun.sun` function by default return times in the UTC timezone and the Location class is not used in the example and . I'll add an example which uses the Location class that by default uses the local timezone.

 If you do the following before printing it out you'll get times closer to what you were expecting

    tz = pytz.timezone(pbmo.timezone)
    s = sun(pbmo.observer, date=datetime.date(2020, 2, 11), tzinfo=tz)

**Comment by jethornton** [comment]
Thanks so much for clearing that up, I look forward to the example.
BTW, you have https://astral.readthedocs.io/en/latest/

> Installation
> To install Astral you should use the pip tool:
> `pip install astral`

I'm sure you mean pip3 for Python 3 
`pip3 install astral`

Thanks
JT

**Comment by jethornton** [comment]
Thanks for fixing the documents

JT
