### ISSUE TITLE
from astral import Astral is not working anymore

### ISSUE THREAD

**Issue by antonakv** [sffjunkie/astral#46]
After update to 2.1 code "from astral import Astral" is not working anymore.

Before it was working with code like:
from astral import Astral
a = Astral()
a.solar_depression = 'civil'

I don't see anything in change-log. What a non pleasant surprise !

**Comment by sffjunkie** [comment]
Sorry for that. I have updated the `Changelog.md` and the version history in the docs to make it more clear that things have been deleted / moved around. It won't help you but it may help others coming to version 2.0
