### ISSUE TITLE
How to extract solar elevation and solar noon in high latitude sites?

### ISSUE THREAD

**Issue by AndrewCunliffe** [sffjunkie/astral#50]
I think this issue is different from, but relates to, issues [9](https://github.com/sffjunkie/astral/issues/9) and [34 ](https://github.com/sffjunkie/astral/issues/34).

I need to compute solar elevation and solar noon for a high latitude location (lat = 70, long= -139), but calling sun (as per the [documentation](https://astral.readthedocs.io/en/latest/index.html)) returns the error "ValueError: Sun never reaches 6.0 degrees below the horizon, at this location". That statement is correct in the summer, but solar noon does happen and there is a solar elevation at that time.

Is there any way to compute just these parameters using astral?

**Comment by mjaviem** [comment]
I think you mean you are calling sun(), right? That method returns dawn times but at that location and day it seems dawn is not happening.

You could call [noon()](https://astral.readthedocs.io/en/latest/package.html#astral.sun.noon) and [elevation()](https://astral.readthedocs.io/en/latest/package.html#astral.sun.elevation) instead, if I'm getting this right.

**Comment by AndrewCunliffe** [comment]
Thanks for the hint @mjaviem, that's exactly what I was looking for.
