### ISSUE TITLE
OSX has issues with urllib and https

### ISSUE THREAD

**Issue by zpriddy** [sffjunkie/astral#6]
I created #5  to change from urllib to requests. 

Yes this does add another package to the requirements but its a common package and fixes some major OSX issues.

**Comment by sffjunkie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OSX https errors](https://trello.com/c/gJ9YMGLe/1-osx-https-errors)

**Comment by sffjunkie** [comment]
Changes merged.
