### ISSUE TITLE
Feature request: Calculate Moon rise and set times

### ISSUE THREAD

**Issue by rct** [sffjunkie/astral#70]
It would be helpful if Astral could be used to calculate moon rise and set times in addition to phase of the moon. 

I'm hoping this would be somewhat in scope for Astral since it is already calculating moon phase. 

Support for moon rise and set would be useful in projects like Home Assistant that use Astral.
- https://community.home-assistant.io/t/moon-rise-set/50896

**Comment by Misiu** [comment]
@sffjunkie any chance this might get added?
There is a PR that supports that: https://github.com/sffjunkie/astral/pull/51

**Comment by galandilias** [comment]
how is it going with the 'timezones funkiness'? :)

**Comment by sffjunkie** [comment]
I've just released v3.0 which includes moon rise and set times as well a azimuth & elevation/zenith
